const serverEndpoint = GM_getValue("serverEndpoint", "https://sponsor.ajay.app")
const thumbEndpoint = GM_getValue("thumbEndpoint","https://sponsor.ajay.app")
const normalization = GM_getValue("normalization", "NFC")
const transform = GM_getValue("transform", "")
const imgfilter = GM_getValue("imgfiler", "")